# 数据处理
#### 得到数据集的纯文本，为embedding做准备

In [1]:
import os
import numpy as np
import cv2
import pandas as pd

## 文本数据处理

In [11]:
after_path = 'C:/Users/wuxun/Desktop/Data/after.txt'

In [12]:
#纯文本存储的位置
path = 'C:/Users/wuxun/Desktop/Data/clear_text.txt'

In [13]:
# count=0
# with open(after_path) as f:
#     with open(path,'w') as f2:
#         for line in f:
#             count+=1
#             if line[0]=='#':
#                 List = line.split('#')
#                 if len(List) != 4:
#                     print("error")
#                 if len(str(List[3])) < 5:
#                     print("error")
#                 L = List[3]
#                 if L[0] == ' ':
#                     L = L[1:]
#                 f2.write(L)

[  4   0   0 ... 154  61 209]
<class 'numpy.ndarray'>
(256, 256, 3)
[200  72  62 ... 253  61 192]
<class 'numpy.ndarray'>
(256, 256, 3)
[210 144  63 ... 178  62 119]
<class 'numpy.ndarray'>
(256, 256, 3)
[147 176  63 ... 107  63 158]
<class 'numpy.ndarray'>
(256, 256, 3)
[119  84  62 ...  14  62   5]
<class 'numpy.ndarray'>
(256, 256, 3)


## frame数据预览

In [21]:
train_test_framepath='C:/Users/wuxun/Desktop/train_csv/101/0O4bxhpFX9o/0001/resnet_34_feat_mscoco.csv'
train_test_framepath2 = 'C:/Users/wuxun/Desktop/train_csv/101/0O4bxhpFX9o/0002/resnet_34_feat_mscoco.csv'

In [3]:
import os  # 文件处理模块，用于处理文件和目录
import torch  # pytorch的深度学习框架
import pandas as pd  #人脸识别库
import numpy as np  # 用于矩阵运算

In [22]:
frame_sum = pd.read_csv(train_test_framepath, header=None)
frame_sum2 = pd.read_csv(train_test_framepath2, header=None)

In [24]:
frame_sum.head(5)#shape:500*512

0         1         2         3         4         5         6    \
0  0.545918  0.241982  0.386552  0.146939  0.140095  0.672740  0.084298   
1  0.816667  0.256795  0.347352  0.145670  0.189268  0.621463  0.061886   
2  0.536372  0.289673  0.299071  0.276259  0.167446  0.699155  0.137488   
3  0.340728  0.220727  0.301987  0.359336  0.256845  0.806340  0.098022   
4  0.602373  0.241626  0.225466  0.253649  0.271959  0.536738  0.126820   

        7         8         9    ...       502       503       504       505  \
0  0.338834  0.138183  0.076534  ...  0.140681  0.136897  0.179613  0.242911   
1  0.267446  0.105320  0.088302  ...  0.185331  0.177433  0.214813  0.209096   
2  0.312030  0.188961  0.076578  ...  0.270337  0.148228  0.085269  0.311521   
3  0.155864  0.170040  0.089696  ...  0.296266  0.143437  0.046236  0.192803   
4  0.332567  0.176165  0.117309  ...  0.349671  0.248874  0.102264  0.216198   

        506       507       508       509       510       511  
0  0.549429  0.231970  0.414309  0.564488  0.219955  0.349501  
1  0.562234  0.231798  0.361083  0.552704  0.208844  0.307647  
2  0.659280  0.334343  0.278230  0.670550  0.244331  0.388888  
3  0.253285  0.505491  0.411379  0.279386  0.208789  0.391478  
4  0.411429  0.683327  0.271618  0.377828  0.259745  0.266378  

[5 rows x 512 columns]

In [25]:
frame_sum2.head(5)

0         1         2         3         4         5         6    \
0  0.554302  0.245196  0.391210  0.142682  0.142631  0.687070  0.075851   
1  0.743370  0.230301  0.359471  0.153871  0.150494  0.630107  0.090259   
2  0.584025  0.281392  0.270861  0.263702  0.198809  0.726478  0.119698   
3  0.333916  0.202119  0.294906  0.347635  0.254798  0.757537  0.107426   
4  0.591243  0.236080  0.244260  0.226722  0.270325  0.524222  0.141667   

        7         8         9    ...       502       503       504       505  \
0  0.339362  0.143334  0.074679  ...  0.135684  0.135910  0.179842  0.235234   
1  0.255920  0.087188  0.062345  ...  0.193191  0.184664  0.176438  0.181039   
2  0.269015  0.154413  0.068885  ...  0.286247  0.155634  0.085392  0.326385   
3  0.147515  0.160049  0.087667  ...  0.330366  0.148713  0.048793  0.257759   
4  0.307274  0.163456  0.106496  ...  0.334080  0.226065  0.114787  0.202007   

        506       507       508       509       510       511  
0  0.540500  0.222853  0.418377  0.554824  0.220742  0.354394  
1  0.585289  0.235385  0.362956  0.623836  0.207694  0.380303  
2  0.587501  0.324534  0.292804  0.646849  0.239270  0.354699  
3  0.248925  0.534307  0.440414  0.260803  0.222323  0.400478  
4  0.437157  0.632099  0.276144  0.417323  0.303216  0.291750  

[5 rows x 512 columns]

## 正式处理

1.先给每个句子加上头部

In [134]:
after_path = 'C:/Users/wuxun/Desktop/Data/after.txt'
after_path1 = 'C:/Users/wuxun/Desktop/Data/after_1.txt'

In [44]:
#确定after文件中开头均无空格

In [97]:
cc=0
lastcc=0
count=0
with open(after_path) as f:
    with open(after_path1, 'w') as f2:
        for line in f:
            count+=1
            if line[0]=='"':
                if line[1:9]=='duration':
                    f2.write(line)
                else:
                    L=line.split('"')
                    str=L[1]
                    if len(str)!=11:
                        print("error")
                    f2.write(str)
            else:
                f2.write(line)
                
#dur中最后一位都是换行符，导数第二位都是'['
#名字中最后一个都是换行符

In [129]:
with open(after_path) as f:
    for line in f:
        if line!='\n' and line[0]!='#':
            L=line.split(',')
            L1=L[0].split(':')
            #name
            #print(L1[0][:11])
            #时长
            #print(L1[1].strip())
            #
            L2=L[1].split(':')
            #数据集类别
            #print(L2[1].strip().strip('"'))
            #菜谱类别
            L3=L[2].split(':')
            print(L3[1].strip().strip('"'))

113
226
105
201
321
107
401
222
120
317
127
304
423
202
325
419
104
323
318
108
102
209
413
418
425
219
215
405
221
405
319
412
202
311
103
228
124
109
301
409
421
412
229
117
309
210
403
109
324
421
307
117
216
418
305
307
101
120
301
302
120
308
419
309
105
120
108
425
324
324
117
216
212
113
116
107
226
205
405
124
223
216
304
305
226
323
101
306
215
308
108
107
325
412
124
107
219
410
110
304
207
207
323
114
218
212
405
210
106
104
102
126
410
227
126
318
204
114
412
410
311
410
225
230
218
410
121
121
112
205
221
406
218
304
121
316
112
418
403
204
206
314
318
211
122
119
102
212
101
418
323
316
213
107
112
122
107
120
405
106
119
325
219
104
401
203
307
317
403
302
301
116
115
305
117
324
205
221
316
413
103
221
224
207
103
225
124
109
208
304
205
126
227
404
317
110
115
221
205
410
122
205
213
122
316
124
209
105
214
212
323
208
101
419
201
105
110
425
221
409
419
412
104
218
213
121
218
225
302
107
313
126
403
215
413
221
119
120
229
421
106
302
215
317
207
113
113
104
412
117


In [143]:
name_line=''
count=0
with open(after_path) as f:
    with open(after_path1, 'w') as f2:
        for line in f:
            if len(line)!=1 and line!='\n':
                if line[0]!='#':
                    L=line.split(',')
                    L1=L[0].split(':')
                    #name
                    #print(L1[0][:11])
                    #时长
                    #print(L1[1].strip())
                    #
                    L2=L[1].split(':')
                    #数据集类别
                    #print(L2[1].strip().strip('"'))
                    #菜谱类别
                    L3=L[2].split(':')
                    #print(L3[1].strip().strip('"'))
                    str=L1[0][:11]+'#'+L1[1].strip()+'#'+L2[1].strip().strip('"')+'#'+L3[1].strip().strip('"')
                    print(str)
                    #print(line)
                    f2.write(str+'\n')
                else:
                    print(line)
                    f2.write(line)

GLd3aX16zBg#241.62#training#113
#114_127#132_138#place the bread slices on top of each other, not a slice of cheese.

#139_145#173_174#cut the sandwich in half, not flip it over.

xHr8X2Wpmno#206.86#validation#226
#47_60#99_137#add verdalago pepper to the lettuce in the bowl, not pick the ends off it .

V53XmPeyjIU#189.36#validation#105
#33_36#46_53#rinse chicken off thoroughly, not place in a small bowl.

#60_89#108_129#coat the chicken pieces in the flour, not place it on a plate.

mZwK0TBI1iY#264.95#validation#201
#44_55#55_78#rub flour onto the chicken, not salt.

#78_96#102_107#top the chicken with mozzarella cheese, not fry it in a pan.

#36_44#111_116#bake the chicken in the oven, not pound it.

XOwypmUT5cc#698.71#training#321
#117_166#175_193#add 2 tbsp corn starch,not cooking oil.

#580_588#600_618#add in the fried chicken, not the corn starch and water mixture. 

#77_98#269_319#mix some corn starch and water together, not sesame seeds.

_xOx9hkJoBk#134.32#training#107
#74_79#

#133_179#185_197# add balsamic vinegar, not sliced tomatoes.

#73_80#82_99# cut the dough with a knife in two halves, not transfer.

cDk1MIsIiQ4#388.4#training#208
#161_220#221_238# remove sausages from the pan, not fry in a pan. 

#68_74#75_81# mash the potatoes, not boil.

UmJk0WSl9Uc#509.36#validation#106
#100_258#294_305# fold in cheese, not chop.

YLmAvKNX0mI#412.68#training#301
#301_355#356_384# add the prepared sauce, not chicken.

#202_250#260_300#fry ginger, not chicken.

#160_195#385_398# add peanuts, not sugar starch.

86Mb6cYFJig#214.57999999999998#validation#410
#100_119#120_127# place the dough on the pan, not roll out.

#57_74#87_91# separate the dough into pieces, not knead.

5nLKfQjYPIc#208.26#training#202
#53_57#76_97# add zucchini to the skillet, not oil.

QuHIxCOkTAo#402.19#training#418
#50_54#118_181# add mixed spices to the pan, not black cumin seeds.

#65_91#234_248# add water to the pan, not chopped white onion.

#256_327#371_394# season the mixture with coriand

In [155]:
laststr=''
with open(after_path) as f:
    with open(after_path1, 'w') as f2:
        for line in f:
            if line[0]=='#':
                str=laststr+line
                print(str)
                f2.write(str)
            else:
                laststr=line[:-1]
                #print(laststr)

GLd3aX16zBg#241.62#training#113#114_127#132_138#place the bread slices on top of each other, not a slice of cheese.

GLd3aX16zBg#241.62#training#113#139_145#173_174#cut the sandwich in half, not flip it over.

xHr8X2Wpmno#206.86#validation#226#47_60#99_137#add verdalago pepper to the lettuce in the bowl, not pick the ends off it .

V53XmPeyjIU#189.36#validation#105#33_36#46_53#rinse chicken off thoroughly, not place in a small bowl.

V53XmPeyjIU#189.36#validation#105#60_89#108_129#coat the chicken pieces in the flour, not place it on a plate.

mZwK0TBI1iY#264.95#validation#201#44_55#55_78#rub flour onto the chicken, not salt.

mZwK0TBI1iY#264.95#validation#201#78_96#102_107#top the chicken with mozzarella cheese, not fry it in a pan.

mZwK0TBI1iY#264.95#validation#201#36_44#111_116#bake the chicken in the oven, not pound it.

XOwypmUT5cc#698.71#training#321#117_166#175_193#add 2 tbsp corn starch,not cooking oil.

XOwypmUT5cc#698.71#training#321#580_588#600_618#add in the fried chicken,

jpQBWsR3HHs#399.94#training#405#178_206#226_238# add some chopped tomatoes, not chopped onions.

jpQBWsR3HHs#399.94#training#405#63_86#320_329# add chopped coriander, not little garam masala.

MIt0YvVC2iY#186.54#training#406#54_61#66_74# place the noodles on the wrapper, not lettuce.

3t0DOJgK1vs#187.55#training#421#21_26#27_33# add the peas to the pan, not oil.

2QtUtQMVoG8#143.98#training#314#103_108#109_119# boil noodles, not egg.

2QtUtQMVoG8#143.98#training#314#88_93#95_98# pour the cabbage into a bowl, not cook in the stock.

BZA7WIwi3aA#359.42#training#204#91_101#101_112# add garlic to the pan, not oil.

BZA7WIwi3aA#359.42#training#204#114_128#189_195# add tomatoes to the pan, not chili flakes.

9CUkuWWVSjE#593.58#training#115#251_269#317_348# dip the hot dog in the batter, not coat in the cornstarch.

jivDSCDoyU0#301.62#training#418#10_39#40_92# add 1 tsp of cumin seeds, not 1 tbsp oil.

jivDSCDoyU0#301.62#training#418#95_134#150_194#add the boiled channa into the pan, not chop

In [161]:
path = 'C:/Users/wuxun/Desktop/Data/cleardata.txt'
path1 = 'C:/Users/wuxun/Desktop/Data/training.txt'
path2 = 'C:/Users/wuxun/Desktop/Data/validation.txt'

In [162]:
with open(path) as f:
    with open(path1, 'w') as f1:
        with open(path2, 'w') as f2:
            for line in f:
                L=line.split('#')
                #print(L[2])
                if L[2]=='training':
                    f1.write(line)
                elif L[2]=='validation':
                    f2.write(line)